name: smart_meet
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.11.0
  # google_maps_flutter: ^2.0.6
  flutter_datetime_picker: ^1.5.1
  geolocator: ^7.0.3
  fluttertoast: ^8.0.7
  image_picker: ^0.8.3
  email_auth: ^0.0.1+4
  string_validator: ^0.3.0
  provider: ^5.0.0
  path_provider: ^2.0.2
  permission_handler:
  dio: ^4.0.0
  google_maps_flutter: ^2.0.3
  intl_phone_number_input: ^0.7.0+2
  shared_preferences: ^2.0.7
  intl: ^0.17.0
  firebase_storage:
  firebase_core:
  date_time_picker: "^2.1.0"
  firebase_ml_vision: ^0.9.6+2
  flutter_polyline_points: ^1.0.0
  google_maps_place_picker:
  place_picker: ^0.9.18
  firebase_messaging: ^10.0.7
  flutter_local_notifications:
  flutter_spinkit: ^5.1.0
  string_extensions:
 




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
